<?php
 $articles = [
     [
         "title" => 'Pourquoi Doom Eternal est certainement le meilleur jeu du monde',
         "hook" => 'Rapide et nerveux, les démons vont en prendre plein la gueule',
         "mark" => 20,
         "content" => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam faucibus dapibus risus, id pretium orci ornare eget. Donec aliquam, leo a tempor hendrerit, odio velit sollicitudin metus, vel porta augue libero ac lacus. Duis viverra ante ac ante venenatis efficitur. Vivamus ultrices efficitur finibus. Vivamus volutpat ultrices tincidunt. Nullam at nisi id nibh tristique eleifend. Sed eleifend augue ut mauris scelerisque mollis. Integer in venenatis ante, id lobortis arcu. Donec sapien nisi, vehicula a posuere a, pharetra eu quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lacinia vulputate risus, non vestibulum dolor tincidunt mollis. Donec blandit eros nulla, id maximus lacus condimentum pharetra. Morbi feugiat luctus accumsan. Proin sed lacinia quam. Phasellus quam lectus, feugiat eget pretium vel, commodo non lectus. Sed dictum eu ipsum in euismod. Suspendisse ac nunc sed quam venenatis imperdiet. In lectus erat, tempor vitae pellentesque sed, luctus a ex. Quisque euismod dolor massa, convallis tristique nisi rutrum non. Mauris condimentum tristique lectus. Etiam vehicula non nulla ac laoreet. Suspendisse ornare ipsum aliquam tortor bibendum, ac rutrum ante blandit. Suspendisse velit elit, mattis ut lacus id, finibus dapibus risus. Aenean luctus quam massa, quis mollis urna rutrum a. In et nibh sed eros rutrum porta ut vel augue. Nunc eu venenatis ligula, in maximus turpis. Vestibulum leo ante, viverra aliquam aliquam id, rutrum quis leo. Vestibulum tincidunt ac diam non posuere. Fusce vitae egestas ligula, quis pretium arcu. Phasellus semper est mauris, id fringilla leo rhoncus non. In rhoncus aliquet massa, et elementum justo sodales viverra. Pellentesque ornare est nibh, eget laoreet justo sollicitudin eget. Curabitur pretium odio ut consectetur maximus. Curabitur ut nibh interdum, vestibulum diam ac, ornare lectus. Nulla facilisi. Maecenas aliquet iaculis egestas. Nullam efficitur sapien nisl, vel vulputate felis congue vitae. Aliquam erat volutpat. Curabitur risus nunc, vulputate in enim et, molestie fermentum dui. Cras a tempus ligula, at imperdiet nibh. Integer ornare libero id justo viverra, vitae sollicitudin massa consequat. Suspendisse ac blandit velit. Sed in sagittis tellus. Donec congue lorem nec ex efficitur vestibulum in et purus. In mollis sed neque in vehicula. In fringilla mi nec velit ullamcorper maximus. Duis tincidunt luctus faucibus. Nunc volutpat ullamcorper tellus, tempor faucibus turpis rutrum nec. Aenean sit amet ex quis erat consectetur eleifend malesuada a mauris. Phasellus eget vestibulum risus. Nullam mollis, lacus at porttitor auctor, dolor ligula facilisis nisi, ut ultricies neque sapien sed libero. Vivamus dapibus egestas libero quis egestas. Sed semper ultricies tempor. Curabitur consequat urna id arcu rutrum, ut maximus odio aliquet. Aliquam ornare enim dolor, a malesuada metus consequat sit amet.',
         "photo" => 'http://image.jeuxvideo.com/medias-md/158516/1585157140-3154-card.jpg'
     ],
     [
         "title" => 'Pourquoi Fortnite est une lamentable bouse pour enfants dégénérés',
         "hook" => 'bla bla bla hook',
         "mark" => 0,
         "content" => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam faucibus dapibus risus, id pretium orci ornare eget. Donec aliquam, leo a tempor hendrerit, odio velit sollicitudin metus, vel porta augue libero ac lacus. Duis viverra ante ac ante venenatis efficitur. Vivamus ultrices efficitur finibus. Vivamus volutpat ultrices tincidunt. Nullam at nisi id nibh tristique eleifend. Sed eleifend augue ut mauris scelerisque mollis. Integer in venenatis ante, id lobortis arcu. Donec sapien nisi, vehicula a posuere a, pharetra eu quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lacinia vulputate risus, non vestibulum dolor tincidunt mollis. Donec blandit eros nulla, id maximus lacus condimentum pharetra. Morbi feugiat luctus accumsan. Proin sed lacinia quam. Phasellus quam lectus, feugiat eget pretium vel, commodo non lectus. Sed dictum eu ipsum in euismod. Suspendisse ac nunc sed quam venenatis imperdiet. In lectus erat, tempor vitae pellentesque sed, luctus a ex. Quisque euismod dolor massa, convallis tristique nisi rutrum non. Mauris condimentum tristique lectus. Etiam vehicula non nulla ac laoreet. Suspendisse ornare ipsum aliquam tortor bibendum, ac rutrum ante blandit. Suspendisse velit elit, mattis ut lacus id, finibus dapibus risus. Aenean luctus quam massa, quis mollis urna rutrum a. In et nibh sed eros rutrum porta ut vel augue. Nunc eu venenatis ligula, in maximus turpis. Vestibulum leo ante, viverra aliquam aliquam id, rutrum quis leo. Vestibulum tincidunt ac diam non posuere. Fusce vitae egestas ligula, quis pretium arcu. Phasellus semper est mauris, id fringilla leo rhoncus non. In rhoncus aliquet massa, et elementum justo sodales viverra. Pellentesque ornare est nibh, eget laoreet justo sollicitudin eget. Curabitur pretium odio ut consectetur maximus. Curabitur ut nibh interdum, vestibulum diam ac, ornare lectus. Nulla facilisi. Maecenas aliquet iaculis egestas. Nullam efficitur sapien nisl, vel vulputate felis congue vitae. Aliquam erat volutpat. Curabitur risus nunc, vulputate in enim et, molestie fermentum dui. Cras a tempus ligula, at imperdiet nibh. Integer ornare libero id justo viverra, vitae sollicitudin massa consequat. Suspendisse ac blandit velit. Sed in sagittis tellus. Donec congue lorem nec ex efficitur vestibulum in et purus. In mollis sed neque in vehicula. In fringilla mi nec velit ullamcorper maximus. Duis tincidunt luctus faucibus. Nunc volutpat ullamcorper tellus, tempor faucibus turpis rutrum nec. Aenean sit amet ex quis erat consectetur eleifend malesuada a mauris. Phasellus eget vestibulum risus. Nullam mollis, lacus at porttitor auctor, dolor ligula facilisis nisi, ut ultricies neque sapien sed libero. Vivamus dapibus egestas libero quis egestas. Sed semper ultricies tempor. Curabitur consequat urna id arcu rutrum, ut maximus odio aliquet. Aliquam ornare enim dolor, a malesuada metus consequat sit amet.',
         "photo" => 'https://cdn2.unrealengine.com/Fortnite%2Fblog%2Fchapter-2-season-2-update%2F11BR_Evergreens_Blue_NewsHeader-1920x1080-77ade2f5f2bc0312b4978dcd7639adfe00211fe6.jpg'
     ]
 ];
